image: node:10.15.0

pipelines:
  default:
    - step:
        name: 'Build Docker image'
        deployment: Test
        script:
          - docker build . -t sparkcoders/elearning-web:latest
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker push sparkcoders/elearning-web:latest
        services:
          - docker
